# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/cpm/cpm.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpm || ORIG_REF_NAME==cpm} -quiet] -quiet

# IP: bd/cpm/ip/cpm_jtag_axi_0_0/cpm_jtag_axi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpm_jtag_axi_0_0 || ORIG_REF_NAME==cpm_jtag_axi_0_0} -quiet] -quiet

# IP: bd/cpm/ip/cpm_axi_gpio_0_0/cpm_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpm_axi_gpio_0_0 || ORIG_REF_NAME==cpm_axi_gpio_0_0} -quiet] -quiet

# IP: bd/cpm/ip/cpm_axi_gpio_1_0/cpm_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpm_axi_gpio_1_0 || ORIG_REF_NAME==cpm_axi_gpio_1_0} -quiet] -quiet

# IP: bd/cpm/ip/cpm_axi_bram_ctrl_0_0/cpm_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpm_axi_bram_ctrl_0_0 || ORIG_REF_NAME==cpm_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/cpm/ip/cpm_blk_mem_gen_0_0/cpm_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpm_blk_mem_gen_0_0 || ORIG_REF_NAME==cpm_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/cpm/ip/cpm_clk_wiz_0/cpm_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpm_clk_wiz_0 || ORIG_REF_NAME==cpm_clk_wiz_0} -quiet] -quiet

# IP: bd/cpm/ip/cpm_rst_clk_wiz_100M_0/cpm_rst_clk_wiz_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpm_rst_clk_wiz_100M_0 || ORIG_REF_NAME==cpm_rst_clk_wiz_100M_0} -quiet] -quiet

# IP: bd/cpm/ip/cpm_smartconnect_0_0/cpm_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpm_smartconnect_0_0 || ORIG_REF_NAME==cpm_smartconnect_0_0} -quiet] -quiet

# IP: bd/cpm/ip/cpm_reset_inv_0_0/cpm_reset_inv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpm_reset_inv_0_0 || ORIG_REF_NAME==cpm_reset_inv_0_0} -quiet] -quiet

# IP: bd/cpm/ip/cpm_ila_0_0/cpm_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpm_ila_0_0 || ORIG_REF_NAME==cpm_ila_0_0} -quiet] -quiet

# XDC: /home/cameronbarrett/ece194bb/project/final.gen/sources_1/bd/cpm/cpm_ooc.xdc
