#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : cpm.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Sat Jun 07 21:58:23 PDT 2025
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# Tool Version Limit: 2022.04 
#
# usage: cpm.sh [-help]
# usage: cpm.sh [-lib_map_path]
# usage: cpm.sh [-noclean_files]
# usage: cpm.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'cpm.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Set vlogan compile options
vlogan_opts="-full64"

# Set vhdlan compile options
vhdlan_opts="-full64"

# Set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc+pp+dmptf -t ps -licqueue -l elaborate.log"

# Set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm jtag_axi xil_defaultlib axi_lite_ipif_v3_0_4 lib_cdc_v1_0_2 interrupt_control_v3_1_4 axi_gpio_v2_0_28 axi_bram_ctrl_v4_1_6 blk_mem_gen_v8_4_5 proc_sys_reset_v5_0_13 xlconstant_v1_1_7 smartconnect_v1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_26 axi_vip_v1_1_12 util_vector_logic_v2_0_2)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "cpm.sh - Script generated by export_simulation (Vivado v2022.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/4e49" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/fd26/hdl/verilog" +incdir+"/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/4e49" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/fd26/hdl/verilog" +incdir+"/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "/ece/Xilinx/Vivado/2022.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/ece/Xilinx/Vivado/2022.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "/ece/Xilinx/Vivado/2022.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/ece/Xilinx/Vivado/2022.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work jtag_axi $vlogan_opts +v2k +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/4e49" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/fd26/hdl/verilog" +incdir+"/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/7ec7/hdl/jtag_axi_v1_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/4e49" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/fd26/hdl/verilog" +incdir+"/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cpm/ip/cpm_jtag_axi_0_0/sim/cpm_jtag_axi_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_28 $vhdlan_opts \
    "$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/3ed9/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/cpm/ip/cpm_axi_gpio_0_0/sim/cpm_axi_gpio_0_0.vhd" \
    "$ref_dir/../../../bd/cpm/ip/cpm_axi_gpio_1_0/sim/cpm_axi_gpio_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_bram_ctrl_v4_1_6 $vhdlan_opts \
    "$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/3c31/hdl/axi_bram_ctrl_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/cpm/ip/cpm_axi_bram_ctrl_0_0/sim/cpm_axi_bram_ctrl_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/4e49" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/fd26/hdl/verilog" +incdir+"/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/25a8/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/4e49" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/fd26/hdl/verilog" +incdir+"/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cpm/ip/cpm_blk_mem_gen_0_0/sim/cpm_blk_mem_gen_0_0.v" \
    "$ref_dir/../../../bd/cpm/ip/cpm_clk_wiz_0/cpm_clk_wiz_0_clk_wiz.v" \
    "$ref_dir/../../../bd/cpm/ip/cpm_clk_wiz_0/cpm_clk_wiz_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/cpm/ip/cpm_rst_clk_wiz_100M_0/sim/cpm_rst_clk_wiz_100M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/4e49" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/fd26/hdl/verilog" +incdir+"/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/4e49" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/fd26/hdl/verilog" +incdir+"/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_0/sim/bd_34b4_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_1/sim/bd_34b4_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/4e49" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/fd26/hdl/verilog" +incdir+"/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
    "$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/c012/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/4e49" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/fd26/hdl/verilog" +incdir+"/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_2/sim/bd_34b4_arinsw_0.sv" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_3/sim/bd_34b4_rinsw_0.sv" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_4/sim/bd_34b4_awinsw_0.sv" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_5/sim/bd_34b4_winsw_0.sv" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_6/sim/bd_34b4_binsw_0.sv" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_7/sim/bd_34b4_aroutsw_0.sv" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_8/sim/bd_34b4_routsw_0.sv" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_9/sim/bd_34b4_awoutsw_0.sv" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_10/sim/bd_34b4_woutsw_0.sv" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_11/sim/bd_34b4_boutsw_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/4e49" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/fd26/hdl/verilog" +incdir+"/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/66be/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/4e49" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/fd26/hdl/verilog" +incdir+"/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_12/sim/bd_34b4_arni_0.sv" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_13/sim/bd_34b4_rni_0.sv" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_14/sim/bd_34b4_awni_0.sv" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_15/sim/bd_34b4_wni_0.sv" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_16/sim/bd_34b4_bni_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/4e49" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/fd26/hdl/verilog" +incdir+"/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/ea34/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/4e49" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/fd26/hdl/verilog" +incdir+"/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_17/sim/bd_34b4_s00mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/4e49" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/fd26/hdl/verilog" +incdir+"/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/4fd2/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/4e49" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/fd26/hdl/verilog" +incdir+"/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_18/sim/bd_34b4_s00tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/4e49" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/fd26/hdl/verilog" +incdir+"/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/8047/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/4e49" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/fd26/hdl/verilog" +incdir+"/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_19/sim/bd_34b4_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/4e49" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/fd26/hdl/verilog" +incdir+"/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/f38e/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/4e49" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/fd26/hdl/verilog" +incdir+"/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_20/sim/bd_34b4_s00a2s_0.sv" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_21/sim/bd_34b4_sarn_0.sv" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_22/sim/bd_34b4_srn_0.sv" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_23/sim/bd_34b4_sawn_0.sv" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_24/sim/bd_34b4_swn_0.sv" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_25/sim/bd_34b4_sbn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/4e49" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/fd26/hdl/verilog" +incdir+"/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/9cc5/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/4e49" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/fd26/hdl/verilog" +incdir+"/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_26/sim/bd_34b4_m00s2a_0.sv" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_27/sim/bd_34b4_m00arn_0.sv" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_28/sim/bd_34b4_m00rn_0.sv" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_29/sim/bd_34b4_m00awn_0.sv" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_30/sim/bd_34b4_m00wn_0.sv" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_31/sim/bd_34b4_m00bn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/4e49" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/fd26/hdl/verilog" +incdir+"/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/6bba/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/4e49" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/fd26/hdl/verilog" +incdir+"/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_32/sim/bd_34b4_m00e_0.sv" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_33/sim/bd_34b4_m01s2a_0.sv" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_34/sim/bd_34b4_m01arn_0.sv" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_35/sim/bd_34b4_m01rn_0.sv" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_36/sim/bd_34b4_m01awn_0.sv" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_37/sim/bd_34b4_m01wn_0.sv" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_38/sim/bd_34b4_m01bn_0.sv" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_39/sim/bd_34b4_m01e_0.sv" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_40/sim/bd_34b4_m02s2a_0.sv" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_41/sim/bd_34b4_m02arn_0.sv" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_42/sim/bd_34b4_m02rn_0.sv" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_43/sim/bd_34b4_m02awn_0.sv" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_44/sim/bd_34b4_m02wn_0.sv" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_45/sim/bd_34b4_m02bn_0.sv" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/ip/ip_46/sim/bd_34b4_m02e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/4e49" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/fd26/hdl/verilog" +incdir+"/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/bd_0/sim/bd_34b4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/4e49" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/fd26/hdl/verilog" +incdir+"/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/4e49" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/fd26/hdl/verilog" +incdir+"/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/0a3f/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_12 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/4e49" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/fd26/hdl/verilog" +incdir+"/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/1033/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/4e49" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/fd26/hdl/verilog" +incdir+"/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cpm/ip/cpm_smartconnect_0_0/sim/cpm_smartconnect_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work util_vector_logic_v2_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/4e49" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/fd26/hdl/verilog" +incdir+"/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/3d84/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/4e49" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../final.gen/sources_1/bd/cpm/ipshared/fd26/hdl/verilog" +incdir+"/ece/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cpm/ip/cpm_reset_inv_0_0/sim/cpm_reset_inv_0_0.v" \
    "$ref_dir/../../../bd/cpm/ip/cpm_ila_0_0/sim/cpm_ila_0_0.v" \
    "$ref_dir/../../../bd/cpm/sim/cpm.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.cpm xil_defaultlib.glbl -o cpm_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./cpm_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./cpm.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/cameronbarrett/ece194bb/project/final.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key cpm_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc cpm_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./cpm.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: cpm.sh [-help]\n\
Usage: cpm.sh [-lib_map_path]\n\
Usage: cpm.sh [-reset_run]\n\
Usage: cpm.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
